"""Add is_admin to Profile

Revision ID: 81f6c3e6fc95
Revises: a0be8e5a28f5
Create Date: 2025-07-26 16:18:15.754148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f6c3e6fc95'
down_revision = 'a0be8e5a28f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        # **FIX:** Add server_default='false' to handle existing rows
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
