"""Add last_picked_at to streams for round-robin

Revision ID: 8d6aac354735
Revises: 81f6c3e6fc95
Create Date: 2025-07-26 17:43:29.748182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6aac354735'
down_revision = '81f6c3e6fc95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_picked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('streams', schema=None) as batch_op:
        batch_op.drop_column('last_picked_at')

    # ### end Alembic commands ###
