"""Add razorpay_customer_id to profile

Revision ID: a0be8e5a28f5
Revises: 
Create Date: 2025-07-24 23:20:31.841757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0be8e5a28f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('razorpay_customer_id', sa.Text(), nullable=True))
        batch_op.create_unique_constraint(None, ['razorpay_customer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('razorpay_customer_id')

    # ### end Alembic commands ###
